application, containerization and database script.
- Application and containerization done.
- Add `init.sql` script for initialization.
- Fix CI, add local CI script `test-local.sh`.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,12 +1,25 @@
 name: Docker Compose Test
 
 on:
+  push:
+    branches: [ main ]
   pull_request:
     branches: [ main ]
+
+env:
+  SQLX_OFFLINE: true
 
 jobs:
   test-compose:
     runs-on: ubuntu-latest
+
+    env:
+      DB_USER: ${{ secrets.DB_USER }}
+      DB_NAME: ${{ secrets.DB_NAME }}
+
+    defaults:
+      run:
+        working-directory: ./ping-visits
 
     steps:
       - name: Checkout code
@@ -18,7 +31,7 @@ jobs:
       - name: Wait for web to be ready
         run: |
           timeout=60
-          while ! curl -f http://localhost:5000 >/dev/null 2>&1; do
+          while ! curl -f http://localhost >/dev/null 2>&1; do
             ((timeout--))
             if [ $timeout -eq 0 ]; then
               echo "Web service failed to start"
@@ -29,7 +42,7 @@ jobs:
 
       - name: Test web response
         run: |
-          response=$(curl -s http://localhost:5000/ping)
+          response=$(curl -s http://localhost/ping)
           if [[ "$response" != "pong" ]]; then
             echo "Expected 'pong', got: $response"
             exit 1
@@ -38,7 +51,17 @@ jobs:
 
       - name: Test PostgreSQL connection
         run: |
-          docker compose exec -T db pg_isready -U user -d app
+          docker compose exec -T db pg_isready -U "${DB_USER}" -d "${DB_NAME}"
+
+      - name: Test database initialized
+        run: |
+          echo "Checking whether table 'visits' with columns 'ip_address', 'id' and 'created_at' exists"
+          cols=$(docker compose exec -T db psql -U "${DB_USER}" -d "${DB_NAME}" -tAc "SELECT column_name FROM information_schema.columns WHERE table_name='visits' ORDER BY ordinal_position;")
+          if [[ "$cols" != *"id"* || "$cols" != *"ip_address"* || "$cols" != *"created_at"* ]]; then
+            echo "Table 'visits' missing expected columns."
+            exit 1
+          fi
+          echo "Table 'visits' with columns 'id', 'ip_address' and 'created_at' exists!"
 
       - name: Show logs on failure
         if: failure()
